parameters:
    ops_elastica.serializer.circularReferenceHandler:
        - 'Opstalent\ElasticaBundle\Serializer\CircularReferenceHandler'
        - 'handle'

services:
    ops_elastica.serializer:
        class: Symfony\Component\Serializer\Serializer
        arguments:
            -
              - '@opstalent.api_bundle.normalizer.datetime'
              - '@ops_elastica.serializer.normalizer.entity'
              - '@ops_elastica.serializer.normalizer.object'
            - ['@serializer.encoder.json']

    ops_elastica.serializer.normalizer.entity:
        class: Opstalent\ElasticaBundle\Serializer\Normalizer\EntityNormalizer
        public: false
        arguments:
            - '@ops_elastica.repository_factory'
        calls:
            - [setCircularReferenceHandler, ['%ops_elastica.serializer.circularReferenceHandler%']]

    ops_elastica.serializer.normalizer.object:
        parent: 'serializer.normalizer.object'
        public: false
        calls:
            - [setCircularReferenceHandler, ['%ops_elastica.serializer.circularReferenceHandler%']]

    ops_elastica.repository_factory:
        class: Opstalent\ElasticaBundle\Repository\RepositoryFactory
        arguments:
            - '@fos_elastica.config_manager'
            - '@service_container'
            - '@event_dispatcher'
            - '@ops_elastica.query.container_resolver'

    ops_elastica.query.template_resolver_factory:
        class: Opstalent\ElasticaBundle\Query\Template\TemplateResolverFactory
        public: false

    ops_elastica.query.script_score_resolver_factory:
        class: Opstalent\ElasticaBundle\Query\Boost\ScriptScore\ResolverFactory
        public: false

    ops_elastica.query.distribution_provider_factory:
        class: Opstalent\ElasticaBundle\Query\Boost\DistributionProviderFactory
        public: false

    ops_elastica.query.script_score.param_provider_factory:
        class: Opstalent\ElasticaBundle\Query\Boost\ScriptScore\ParamProviderFactory
        public: false

    ops_elastica.query.template_resolver.bool:
        class: Opstalent\ElasticaBundle\Query\Template\BoolTemplateResolver
        arguments:
            - '@ops_elastica.query.template_resolver_factory'
        public: false
        tags:
            - { name: ops_elastica.query_template_resolver }

    ops_elastica.query.template_resolver.dis_max:
        class: Opstalent\ElasticaBundle\Query\Template\DisMaxTemplateResolver
        arguments:
            - '@ops_elastica.query.template_resolver_factory'
        public: false
        tags:
            - { name: ops_elastica.query_template_resolver }

    ops_elastica.query.template_resolver.term_collection:
        class: Opstalent\ElasticaBundle\Query\Template\TermCollectionTemplateResolver
        arguments:
            - '@ops_elastica.query.distribution_provider_factory'
        public: false
        tags:
            - { name: ops_elastica.query_template_resolver }

    ops_elastica.query.template_resolver.subitem_term_collection:
        class: Opstalent\ElasticaBundle\Query\Template\SubitemTermCollectionTemplateResolver
        arguments:
            - '@ops_elastica.query.distribution_provider_factory'
        public: false
        tags:
            - { name: ops_elastica.query_template_resolver }

    ops_elastica.query.template_resolver.function_score:
        class: Opstalent\ElasticaBundle\Query\Template\FunctionScoreTemplateResolver
        arguments:
            - '@ops_elastica.query.template_resolver_factory'
            - '@ops_elastica.query.script_score_resolver_factory'
        public: false
        tags:
            - { name: ops_elastica.query_template_resolver }

    ops_elastica.query.script_score_resolver.script:
        class: Opstalent\ElasticaBundle\Query\Boost\ScriptScore\ScriptResolver
        public: false
        arguments:
            - '@ops_elastica.query.script_score.param_provider_factory'
        tags:
            - { name: ops_elastica.query_script_score_resolver }

    ops_elastica.query.container_resolver:
        class: Opstalent\ElasticaBundle\Query\Template\ContainerResolver
        public: false
        arguments:
            - '@ops_elastica.query.template_resolver_factory'
